### PR TITLE
Update to fix M1 Silicon Driver issue

### PR DESCRIPTION
**Pull request by Austin1**
I have literally no idea what I'm doing, but I've stumbled far enough through to maybe have fixed it with a simple package upgrade.

I was doing research and trying to enable build dependencies, which I never figured out, but in the process of my research I found some info on the nodejs driver for Teradata that made me believe maybe upgrading to the latest version would work. So after getting error after error, I finally got it to build after re-running npm install and it worked!

So I just tested a connection to a teradata database successfully using the newest nodejs driver.

I see package-lock.json in my commit, which I dont know if that's supposed to be here or not, but I'm leaving so you can decide.

Hopefully this works!

### CODE REVIEW

**Comment by ScriptPup** [comment]
Hi @Austin1,
The package-lock.json is the exact specifications of what you have installed within the project regardless of what's been saved in the package.json file. If I'm understanding you correctly, there was some kind of bug that you solved by updating the `teradata-nodejs-driver`. 

What error were you getting that this fixed? We'll need to update the package.json, not just the package-lock.json, but other than that no additional changes would be needed to approve the PR. :) 

(Sorry for the delay, been out for a while)

**Comment by Austin1** [comment]
I actually didn't mean to submit the json-lock file. This seems to solve this issue: https://github.com/ScriptPup/sqltools-teradata-driver/issues/12 - i didn't know how to link it all together so it was easy to review. Sorry

**Comment by ScriptPup** [comment]
Sorry, just haven't had much time to spin up a test Teradata instance to test before merging to main. In the middle of a long moving process :) Will try and get to that soon

**Comment by Austin1** [comment]
If you want to send me a compiled version of the extension with your
changes I can send you some screenshots showing if it works with teradata
from a Mac or Windows machine.

Now, I might not conform to all the test you would normally run but I can
at least validate that it connects in my environment and works.

If that's helpful in anyway.

**Comment by ScriptPup** [comment]
Sorry for the delay, finally in a position to test this against a teradata environment. Need to get a docker container setup or something for automated testing.

Seems to work fine from what I see, thanks!

**Pull request merged**
